name: fast_apir Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SSH Deploy
        env:
          SERVER_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
          HOST_NAME: "${{ secrets.HOST_NAME }}"
          USER_NAME: "${{ secrets.USER_NAME }}"
          PROJECT_PATH: "${{ secrets.PROJECT_PATH }}"
          GIT_REPO: "${{ secrets.GIT_REPO }}"
          SSH_PORT: 22
        run: |
          echo "Configurando clave SSH para conectar al servidor"
          mkdir -p ~/.ssh
          echo "$SERVER_PRIVATE_KEY" > ~/.ssh/server_key
          chmod 600 ~/.ssh/server_key
          ssh-keyscan -H $HOST_NAME >> ~/.ssh/known_hosts

          echo "Conectando al servidor por SSH y desplegando..."
          ssh -i ~/.ssh/server_key -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} <<EOF
            mkdir -p \$(dirname ${PROJECT_PATH})

            if [ ! -d "${PROJECT_PATH}/.git" ]; then
              git clone ${GIT_REPO} ${PROJECT_PATH}
            fi

            cd ${PROJECT_PATH}
            git fetch --all
            git reset --hard origin/main
            git pull origin main
          EOF
